### ISSUE TITLE
Which version of Caffe do you use for training?

### ISSUE THREAD

**Issue by baiyancheng20** [cvjena/cnn-models#1]
Hi, interesting work. I want to know which version of Caffe you use for training. And could you give a detail on how to train the resnet model?

**Comment by MarcelSimon** [comment]
I used a normal Caffe cloned back in May (should be hash e79bc8f1f6df4db3a293ef057b7ca5299c01074a)

The training is described in the paper as well as in the proto files for the solver and network definition. I adapted the solver and definition files a bit for publication, but the logs contain all the original parameters used in training.

Do you have any specific questions?

**Comment by baiyancheng20** [comment]
Thank you. I just want to make sure the version of Caffe because I tried to learn new models but not failed. Thank you.
