### ISSUE TITLE
Why there is no scale layer after each batch norm layer?

### ISSUE THREAD

**Issue by Microos** [cvjena/cnn-models#11]
I found only the BN layer after the data layer is followed by a scale layer, but other BN layers are not cooperating with scale layers? Does it because the VGG is using ReLU instead of Sigmoid as its activation function? Thanks.

**Comment by MarcelSimon** [comment]
There is no special reason for that, it's merely a choice of architecture. It saves memory and at least for AlexNet, accuracy is very similar compared to using a scale layer.

**Comment by Microos** [comment]
I see. Thanks for the answer.
