### ISSUE TITLE
Worse performance than the reported one in Res50

### ISSUE THREAD

**Issue by AIROBOTAI** [cvjena/cnn-models#12]
Hi Developers,

I have trained the Res50 using the provided scripts, however I get worse performance as below: 
```
Test net output #0: acc/top-1 = 0.739239
Test net output #1: acc/top-5 = 0.919044
```
In comparison, the reported performance is top-1/top-5 = 24.6%/7.6%. The only difference between my training and yours is I use 4 gpus in parallel as well as change the `iter_size` in `train.solver` from 8 to 4 such that the overall batch size remains the same. Could you please tell me where the gap comes from? Thanks in advance!

**Comment by MarcelSimon** [comment]
Hi!

This previous issue might be relevant: https://github.com/cvjena/cnn-models/issues/9

How did you preprocess your images?

**Comment by AIROBOTAI** [comment]
Thanks for your quick reply! @MarcelSimon 
Yes, my problem might be the same as #9 and I also use the LMDB format with all images resizing to 256x256. Thanks for your remind! I'll try your image preprocessing way.
