### ISSUE TITLE
Would you mind share labels file?

### ISSUE THREAD

**Issue by stormanger** [cvjena/cnn-models#15]
Hello Simon
Would you mind share labels file?
I want use Digits for cnn-models test, It required a labels file.
Thank you

**Comment by MarcelSimon** [comment]
What exactly do you mean by labels file? You mean the train and test lists?

**Comment by stormanger** [comment]
The labels for 1000 of categories, The file contains a list of categories
$ cat labels.txt
apple
banana
bread
keyboard
lemon

**Comment by MarcelSimon** [comment]
So you mean the class names? It's available in the caffe ilsvrc dev kit: http://dl.caffe.berkeleyvision.org/caffe_ilsvrc12.tar.gz
