### ISSUE TITLE
Would you mind sharing VGG16 model? 

### ISSUE THREAD

**Issue by baiyancheng20** [cvjena/cnn-models#16]
Would you mind sharing VGG16 model with BN since many works are based on that model?

**Comment by MarcelSimon** [comment]
Unfortunately, I did not train a VGG16 model as it takes months on a single GPU. In case you want to give it a shot, just remove the three layers added in VGG19 and train it. I would be happy if you could share it with us.

**Comment by mrgransky** [comment]
There seems to be a typo in ur website regarding VGG16 which brings some confusion!

![cnn_model](https://user-images.githubusercontent.com/11946010/78924279-2f97f580-7aa2-11ea-8976-c27d9276aeb6.png)
