### ISSUE TITLE
Inception models & weights

### ISSUE THREAD

**Issue by vimalthilak** [cvjena/cnn-models#2]
Hi,

Do you have any plans to train & release Inception v1, v3 & v4 models?

Thanks,

-Vimal

**Comment by MarcelSimon** [comment]
Hi Vimal! 

I have implemented Inception v4, but unfortunately did not have the time to train it yet. 

Cheers, Marcel

**Comment by vimalthilak** [comment]
Hi Marcel,
Thanks for the quick response. Would you be able to share if you plan to train v4 soon or if you have a resource unavailable to train the model anytime soon? 
On the other hand, if you have started training, I would love to hear any insights you might have for training Inception v4 from scratch. Thanks

**Comment by MarcelSimon** [comment]
Hi Vimal!
I will train a small version of the Inception v4 soon. So far, using the parameters mentioned in the paper seemed to work well. However, I did not run the full training yet.
