### ISSUE TITLE
VGG19BN: weird values of 'data/bn' parameters.

### ISSUE THREAD

**Issue by zeakey** [cvjena/cnn-models#20]
I found that the parameters of `data/bn` in [vgg19bm]() has mean value `1127.633`, a very weird value.

I know the mean of imagenet images are nearby `112`, so why the parameters of `data/bn` is `1127`, ten times of 112.

And I noticed that you datalayer reads data from `/home/atlas1_ssd/simon/ilsvrc12-scaled/train/` (<https://github.com/cvjena/cnn-models/blob/master/VGG19_cvgj/train.prototxt#L18>). There is a `scaled` in your folder name.

So I guess you have scaled the raw image with factor 10, right?

![tim 20180116145158](https://user-images.githubusercontent.com/6763078/34975469-d3f918dc-facc-11e7-8c92-792ac3fa1248.png)

**Comment by MarcelSimon** [comment]
The param[2] of a batch norm layer contains the multiplier. If I'm not mistaken, the real mean is param[0]/param[2]. Please refer to the batch norm layer implementation of caffe for more details. So the reading of param[0] seems to be ok, but I think there is a bug in your script for reading param[1] and param[2].

**Comment by mrgransky** [comment]
How did u get the `mean` and `std` of each param? what was ur script to print them?
