### ISSUE TITLE
No image mean subtraction for models 

### ISSUE THREAD

**Issue by fshi98** [cvjena/cnn-models#4]
I see you that there is no image mean subtraction. I'm just wonder if this is an implementation choice or determined by experiments.

**Comment by MarcelSimon** [comment]
It was an idea I had when creating the models. The static mean used in previous models is a special case of the batch norm mean used in my models. In theory, my aproach is more powerful. However, I did not run any proper evaluation on this yet.

**Comment by mrgransky** [comment]
in ur website, there seems to be a typo regarding VGG16!
![cnn_model](https://user-images.githubusercontent.com/11946010/78924159-fcedfd00-7aa1-11ea-9df5-e9dc756771a4.png)
