### ISSUE TITLE
Questions of source and root_folder in train.prototxt

### ISSUE THREAD

**Issue by larsonwu0220** [cvjena/cnn-models#6]
I have two questions when I review train.prototxt.
1.
 ```
image_data_param {
    source: "/home/atlas2_ssd/simon/ilsvrc12/train.txt"
    batch_size: 128
    shuffle: true
    root_folder: "/home/atlas1_ssd/simon/ilsvrc12-scaled/train/"
    }
```
 Can I replace the source type to LMDB?
2.  How to form root_folder(scaled) of my own data? 

Thanks a lot !

**Comment by MarcelSimon** [comment]
Hi! 
1. You can replace the image data layer by lMDB. The difference is, that a LMDB dataset transforms all images to be square shape and hence changes the aspect ratio. The image data layer preserves the aspect ratio, hence the results might vary a bit.
2. You can use the linux tool convert to resize all images in a folder. Do something like find . -name "*.JPEG" and pipe it to convert. These scaled images are only useful for the image data layer though.
